apiVersion: v1
data:
  ADDRESS: bWJla2FzLXBvcnRmb2xpby5jbGljaw==
  BACKEND_SERVICE: YXBwLWJhY2tlbmQtaGVsbQ==
kind: Secret
metadata:
  creationTimestamp: "2022-11-17T13:46:28Z"
  name: my-secret2
  namespace: default
  resourceVersion: "284122"
  uid: 1aae95e7-53a4-4ebb-ad9d-12e3c79edde7
type: Opaque
