apiVersion: v1
kind: Service
metadata:
  name: ingress-prometheus
spec:
  ports:
  - name: ingress-prometheus
    port: 80
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-ingress-nginx-ingress
  type: ClusterIP
