apiVersion: v2
appVersion: 2.4.1
description: NGINX Ingress Controller
home: https://github.com/nginxinc/kubernetes-ingress
icon: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v2.4.1/deployments/helm-chart/chart-icon.png
keywords:
- ingress
- nginx
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: kubernetes@nginx.com
  name: nginxinc
name: app
sources:
- https://github.com/nginxinc/kubernetes-ingress/tree/v2.4.1/deployments/helm-chart
type: application
version: 0.15.1
dependencies:
- name: threetier
  version: 0.1.0
