apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio  #name of this object
spec:
  dnsNames:
    - mbekas-portfolio.ddns.net
  secretName: portfolio
  issuerRef:
    name: letsencrypt
    kind: Issuer
