apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert  #name of this object
spec:
  dnsNames:
    - mbekasportfolio.ddns.net
  secretName: cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
