apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullhelmapp.fullname" . }}
  labels:
    {{- include "fullhelmapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    {{- include "fullhelmapp.selectorLabels" . | nindent 4 }}
